project:
  type: website
  output-dir: docs

website:
  title: "Luke Morris"
  description: "Healthcare Data Analytics | Data Science | R | Quarto"
  site-url: https://morrisLuke.github.io/
  repo-url: https://github.com/morrisLuke/morrisLuke.github.io
  navbar:
    right:
      - text: blog
        href: blog.qmd
      - icon: mastodon
        href: https://fosstodon.org/@lukemorris
      - icon: linkedin
        href: https://www.linkedin.com/in/lukesmorris/
      - icon: github
        href: https://github.com/morrisLuke
  google-analytics: "G-60SLVZ7V99"
  cookie-consent: true
format:
  html:
    theme:
      - yeti
      - custom.scss
    css: styles.css

editor: visual

