project:
  type: website
  output-dir: docs

website:
  title: "Luke S. Morris"
  description: "Healthcare Data Science | R | Quarto"
  site-url: https://morrisLuke.github.io/
  repo-url: https://github.com/morrisLuke/morrisLuke.github.io
  navbar:
    right:
      - text: blog
        href: blog.qmd
      - text: "<i class='fa-brands fa-linkedin'></i>"
        href: https://www.linkedin.com/in/lukesmorris/
      - text: "<i class='fa-brands fa-github'></i>"
        href: https://github.com/morrisLuke
      - text: "<i class='fa-brands fa-bluesky'></i>"
        href: https://bsky.app/profile/luke-morris.bsky.social
      - text: "<i class='fa-brands fa-mastodon'></i>"
        href: https://rstats.me/@luke_morris
  google-analytics: "G-60SLVZ7V99"
  cookie-consent: true
format:
  html:
    theme:
      - darkly
    email-obfuscation: javascript
drafts:
 - posts/new_post/dummy_post.qmd
draft-mode: unlinked

editor: visual

