project:
  type: website
  output-dir: docs

website:
  title: "Luke S. Morris"
  description: "Healthcare Data Science | R | Quarto"
  site-url: https://morrisLuke.github.io/
  repo-url: https://github.com/morrisLuke/morrisLuke.github.io
  navbar:
    right:
      - text: blog
        href: blog.qmd
      - text: "{{< iconify fa6-brands linkedin >}}"
        aria-label: linkedin
        href: https://www.linkedin.com/in/lukesmorris/
      - text: "{{< iconify fa6-brands github >}}"
        aria-label: github
        href: https://github.com/morrisLuke
      - text: "{{< iconify fa6-brands bluesky >}}"
        aria-label: bluesky
        href: https://bsky.app/profile/lukesmorris.com
      - text: "{{< iconify fa6-brands mastodon >}}"
        aria-label: mastodon
        href: https://rstats.me/@luke_morris
  google-analytics: "G-60SLVZ7V99"
  cookie-consent: true
format:
  html:
    theme:
      - darkly
    email-obfuscation: javascript
drafts:
 - posts/new_post/dummy_post.qmd
draft-mode: unlinked

editor: visual

